CREATE TABLE project_members
(
    created_at               TIMESTAMP WITHOUT TIME ZONE,
    updated_at               TIMESTAMP WITHOUT TIME ZONE,
    created_by               VARCHAR(100),
    updated_by               VARCHAR(100),
    project_role             VARCHAR(40) NOT NULL,
    participation_start_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    expected_end_time        TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    project_id               BIGINT      NOT NULL,
    user_id                  BIGINT      NOT NULL,
    CONSTRAINT pk_project_members PRIMARY KEY (project_id, user_id)
);

CREATE TABLE projects
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    deleted_at TIMESTAMP WITHOUT TIME ZONE,
    deleted_by VARCHAR(100),
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    created_by VARCHAR(100),
    updated_by VARCHAR(100),
    name       VARCHAR(255)                            NOT NULL,
    status     VARCHAR(30)                             NOT NULL,
    start_time TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    end_time   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_projects PRIMARY KEY (id)
);

CREATE TABLE tasks
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    deleted_at  TIMESTAMP WITHOUT TIME ZONE,
    deleted_by  VARCHAR(100),
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    created_by  VARCHAR(100),
    updated_by  VARCHAR(100),
    project_id  BIGINT                                  NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    status      VARCHAR(30)                             NOT NULL,
    assignee_id BIGINT                                  NOT NULL,
    start_time  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    deadline    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_tasks PRIMARY KEY (id)
);

CREATE INDEX idx_projects_deleted_at ON projects (deleted_at);

CREATE INDEX idx_projects_status ON projects (status);

CREATE INDEX idx_tasks_deleted_at ON tasks (deleted_at);

CREATE INDEX idx_tasks_status ON tasks (status);

ALTER TABLE project_members
    ADD CONSTRAINT FK_PROJECT_MEMBERS_ON_PROJECT FOREIGN KEY (project_id) REFERENCES projects (id);

ALTER TABLE project_members
    ADD CONSTRAINT FK_PROJECT_MEMBERS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE tasks
    ADD CONSTRAINT FK_TASKS_ON_ASSIGNEE FOREIGN KEY (assignee_id) REFERENCES users (id);

CREATE INDEX idx_tasks_assignee_id ON tasks (assignee_id);

ALTER TABLE tasks
    ADD CONSTRAINT FK_TASKS_ON_PROJECT FOREIGN KEY (project_id) REFERENCES projects (id);

CREATE INDEX idx_tasks_project_id ON tasks (project_id);

